config/routes.rb
Rails.application.routes.draw do

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  root to: 'visitors#index'

  match '/about', to: 'pages#about', via: 'get'

  devise_for :users
  resources :users

  get '/controls', to: 'robot#index', as: 'controls'
  get '/set_command', to: 'robot#command', as: 'set_command'
  get '/delete_history', to: 'robot#destroy', as: 'delete_history'

  namespace :api do
    get '/command', to: 'robot#index', as: 'command'
    get '/executed', to: 'robot#update', as: 'executed'
  end


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/robot.rb
class Robot < ApplicationRecord
  self.table_name = "robot"

  def self.clean_history
    @history = self.where.not(id: self.all.last)
    @count = @history.count
    @history.delete_all

    return "#{@count} commands cleaned from history!"
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/api/robot_controller.rb
class Api::RobotController < ApiController

  # GET /api/command
  def index
    @robot = Robot.last
    render json: @robot
  end

  # GET /api/executed
  def update
    @robot = Robot.last
    if @robot.update(:executed => 'true')
      render json: @robot
    else
      render json: @robot.errors, status: :unprocessable_entity
    end
  end

end

app/controllers/api_controller.rb
class ApiController < ActionController::API
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?
  after_action :clean_command_history
  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name])
  end

  def clean_command_history
    @history = Robot.where.not(id: Robot.all.last)
    if @history.count >= 9000
      @history.delete_all
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def about
  end

end

app/controllers/robot_controller.rb
class RobotController < ApplicationController
  before_action :authenticate_user!

  def index
  end

  def command
    @sent_command = params[:command]
    @new_command = Robot.new(:command => @sent_command, :executed => 'false')
    @new_command.save
  end

  def destroy
    @message = Robot.clean_history
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    unless @user == current_user
      redirect_to :back, :alert => "Access denied."
    end
  end

end

app/controllers/visitors_controller.rb
class VisitorsController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-dismissible alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Bootstrap 3.0 %>
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Home', root_path, class: 'navbar-brand' %>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <%= render 'layouts/navigation_links' %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_navigation_links.html.erb
<% if user_signed_in? %>
    <li><%= link_to 'Controls', controls_path %></li>
    <li><%= link_to 'About', about_path %></li>
    <li><%= link_to 'Delete History', delete_history_path %></li>
    <li><%= link_to 'Admin', rails_admin_path %></li>
    <li><%= link_to 'Edit account', edit_user_registration_path %></li>
    <li><%= link_to 'Sign out', destroy_user_session_path, :method=>'delete' %></li>

<% else %>
    <li><%= link_to 'Sign in', new_user_session_path %></li>
    <li><%= link_to 'Sign up', new_user_registration_path %></li>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Baxter Control</title>
    <meta name="description" content="Baxter Control">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <header>
      <%= render 'layouts/navigation' %>
    </header>
    <div style="margin-top: 50px;">
       <%= render 'layouts/messages' %>
       <%= yield %>
    </div>
  </body>
</html>

app/views/pages/about.html.erb
<div class="container">
    <div class="row">
        <h1 class="text-center">This site was developed to provide a REST API for controlling a Baxter robot!</h1>

    </div>
</div>

app/views/robot/destroy.html.erb
<div class="container">
    <div class="row">
        <h1 class="text-center"><%= @message %></h1>
    </div>
</div>

app/views/robot/index.html.erb
<div class="container">
    <div class="row">
        <h1 class="text-center">Baxter Controls</h1>
    </div>
    <div class="row" style="margin-left: 10%; margin-bottom: 20px;">
        <div class="col-md-4 col-md-offset-4 col-xs-10 col-xs-offset-2">
            <%# 2 - Head Neutral %>
            <%= link_to "Head Neutral", set_command_path(:command => '2'), :remote => true, :class => 'btn btn-success', :style => "margin-right: 10px; margin-left: -30px;" %>
            <%# 5 - Arms Neutral %>
            <%= link_to "Arms Neutral", set_command_path(:command => '5'), :remote => true, :class => 'btn btn-success' %>
        </div>
    </div>
    <div class="row" style="margin-left: 10%">
        <div class="col-xs-2">
            <%# 1 - Head Left %>
            <%= link_to "Head Left", set_command_path(:command => '1'), :remote => true, :class => 'btn btn-success pull-right' %>
            <br>
            <br>
            <br>
            <br>
            <br>
            <br>
            <%# 4 - Arms Up %>
            <%= link_to "Arms Up", set_command_path(:command => '4'), :remote => true, :class => 'btn btn-success pull-right' %>
        </div>
        <div class="col-xs-6">
            <img class="img-responsive" src="http://www.hizook.com/files/users/3/Baxter_Robot_from_RethinkRobotics_8.jpg">
        </div>
        <div class="col-xs-2">
            <%# 3 - Head Right %>
            <%= link_to "Head Right", set_command_path(:command => '3'), :remote => true, :class => 'btn btn-success', :style => "margin-bottom: 5px" %>
            <br>
            <br>
            <br>
            <br>
            <br>
            <%# 6 - Arms Wide %>
            <%= link_to "Arms Wide", set_command_path(:command => '6'), :remote => true, :class => 'btn btn-success' %>
        </div>

    </div>

</div>

<script>
    $(document).ready(function(){
        $('a.btn').on('click', function () {
            var $btn = $(this);
            var init_txt = $btn.text();

            $btn.text('Moving...');

            var checkExecuted = function() {

                $.getJSON("/api/command", function (data) {

                }).done(function( data ) {
                    console.log("Command: " + data.command + " Executed: " + data.executed);
                    if (data.executed == 'true'){
                        $btn.text(init_txt);
                        clearInterval(xInt);
                    }
                });
            };

            var xInt = setInterval(checkExecuted, 1000);

        });
    });
</script>

app/views/users/_user.html.erb
<td><%= link_to user.name, user %></td>
<td><%= link_to user.email, user %></td>

app/views/users/index.html.erb
<div class="container">
  <div class="row">
    <h3>Users</h3>
    <div class="column">
      <table class="table">
        <tbody>
          <% @users.each do |user| %>
            <tr>
              <%= render user %>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<h3>User</h3>
<p>Name: <%= @user.name if @user.name %></p>
<p>Email: <%= @user.email if @user.email %></p>

app/views/visitors/index.html.erb
<div class="container">
    <div class="row">
        <h1 class="text-center">Welcome to Baxter Control!</h1>
        <img src="http://www.hizook.com/files/users/3/Baxter_Robot_from_RethinkRobotics_8.jpg" width="50%">
    </div>
</div>